apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: model-registry
  name: mr-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mr-admin-binding
  namespace: model-registry
subjects:
  - kind: Group
    name: "org/ml-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mr-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: model-registry
  name: mr-client
rules:
  - apiGroups: [""]
    resources: ["pods","services","deployments"]
    verbs: ["get","list","watch","create","update","patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mr-client-binding
  namespace: model-registry
subjects:
  - kind: Group
    name: "org/data-science-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mr-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: model-registry
  name: mr-view
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps","secrets"]
    verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mr-view-binding
  namespace: model-registry
subjects:
  - kind: Group
    name: "org/analytics-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mr-view
  apiGroup: rbac.authorization.k8s.io
