apiVersion: v1
kind: ResourceQuota
metadata:
  name: mr-quota
  namespace: model-registry
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 16Gi
    limits.cpu: "8"
    limits.memory: 32Gi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mr-limits
  namespace: model-registry
spec:
  limits:
    - default:
        cpu:  "1"
        memory: "4Gi"
      defaultRequest:
        cpu: "250m"
        memory: "1Gi"
      type: Container
