apiVersion: v1
kind: ResourceQuota
metadata:
  name: de-quota
  namespace: data-engineering
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 32Gi
    limits.cpu: "20"
    limits.memory: 64Gi
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: de-limits
  namespace: data-engineering
spec:
  limits:
    - default:
        cpu:  "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
      type: Container
