apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: inference-online
  name: io-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: io-admin-binding
  namespace: inference-online
subjects:
  - kind: Group
    name: "org/ml-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: io-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: inference-online
  name: io-client
rules:
  - apiGroups: [""]
    resources: ["services","deployments","pods"]
    verbs: ["get","list","watch","create","patch","update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: io-client-binding
  namespace: inference-online
subjects:
  - kind: Group
    name: "org/data-science-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: io-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: inference-online
  name: io-view
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: io-view-binding
  namespace: inference-online
subjects:
  - kind: Group
    name: "org/analytics-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: io-view
  apiGroup: rbac.authorization.k8s.io
