apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: runtimes-sandbox
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-limits
  namespace: runtimes-sandbox
spec:
  limits:
    - default:
        cpu:  "500m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      type: Container
