apiVersion: v1
kind: ResourceQuota
metadata:
  name: infra-ops-quota
  namespace: infra-ops
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 16Gi
    limits.cpu: "12"
    limits.memory: 32Gi
    pods: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: infra-ops-limits
  namespace: infra-ops
spec:
  limits:
    - default:
        cpu:  "1"
        memory: "1Gi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      type: Container
