apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: feature-store
  name: fs-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fs-admin-binding
  namespace: feature-store
subjects:
  - kind: Group
    name: "org/ml-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fs-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: feature-store
  name: fs-client
rules:
  - apiGroups: [""]  
    resources: ["pods","services","deployments"]
    verbs: ["get","list","watch","create","update","patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fs-client-binding
  namespace: feature-store
subjects:
  - kind: Group
    name: "org/ml-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fs-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: feature-store
  name: fs-view
rules:
  - apiGroups: [""]  
    resources: ["pods","services","endpoints"]
    verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fs-view-binding
  namespace: feature-store
subjects:
  - kind: Group
    name: "org/analytics-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fs-view
  apiGroup: rbac.authorization.k8s.io
