apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-system-quota
  namespace: platform-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: platform-system-limits
  namespace: platform-system
spec:
  limits:
    - default:
        cpu:  "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
