apiVersion: v1
kind: ResourceQuota
metadata:
  name: sec-gk-quota
  namespace: security-gatekeeper
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sec-gk-limits
  namespace: security-gatekeeper
spec:
  limits:
    - default:
        cpu:  "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
