apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ci-cd
  name: cicd-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-admin-binding
  namespace: ci-cd
subjects:
  - kind: Group
    name: "org/devops-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cicd-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ci-cd
  name: cicd-runner
rules:
  - apiGroups: ["","apps","batch"]
    resources: ["pods","jobs","deployments"]
    verbs: ["create","get","list","watch","update","patch","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-runner-binding
  namespace: ci-cd
subjects:
  - kind: ServiceAccount
    name: cicd-runner-sa
roleRef:
  kind: Role
  name: cicd-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ci-cd
  name: cicd-view
rules:
  - apiGroups: [""]
    resources: ["pods","jobs","pipelines","pipelinesruns"]
    verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-view-binding
  namespace: ci-cd
subjects:
  - kind: Group
    name: "org/dev-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cicd-view
  apiGroup: rbac.authorization.k8s.io
